"""initial_clean_schema

Revision ID: 70f03626929a
Revises: 
Create Date: 2026-01-01 00:39:30.590780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70f03626929a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', name='contactstatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('donated_for', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('donated_on', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('receipt_generated_at', sa.DateTime(), nullable=True),
    sa.Column('payment_mode', sa.Enum('CASH', 'UPI', 'BANK', 'CHEQUE', name='paymentmode'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_donors_id'), 'donors', ['id'], unique=False)
    op.create_table('festivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('festival_date', sa.Date(), nullable=True),
    sa.Column('festival_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festivals_id'), 'festivals', ['id'], unique=False)
    op.create_table('poojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('pooja_type', sa.String(length=50), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('suggested_amount', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_poojas_id'), 'poojas', ['id'], unique=False)
    op.create_table('temples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('deity_name', sa.String(length=100), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temples_id'), 'temples', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('expense_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('SALARY', 'MATERIAL', 'MAINTENANCE', 'FESTIVAL', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'UPI', 'BANK', 'CHEQUE', name='paymentmode'), nullable=False),
    sa.Column('paid_to', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_transactions_category'), 'expense_transactions', ['category'], unique=False)
    op.create_index(op.f('ix_expense_transactions_payment_mode'), 'expense_transactions', ['payment_mode'], unique=False)
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_id'), 'gallery', ['id'], unique=False)
    op.create_table('income_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('SEVA', 'DONATION', 'HUNDI', 'MANUAL', name='incomesourcetype'), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'UPI', 'BANK', 'CHEQUE', name='paymentmode'), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_transactions_payment_mode'), 'income_transactions', ['payment_mode'], unique=False)
    op.create_index(op.f('ix_income_transactions_source_type'), 'income_transactions', ['source_type'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('emergency_contact', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_table('seva_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('seva_id', sa.Integer(), nullable=False),
    sa.Column('seva_name', sa.String(), nullable=False),
    sa.Column('devotee_name', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('seva_date', sa.Date(), nullable=False),
    sa.Column('seva_time', sa.Time(), nullable=True),
    sa.Column('payment_status', sa.Enum('FREE', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'CANCELLED', name='ticketstatus'), nullable=False),
    sa.Column('source', sa.Enum('ONLINE', 'COUNTER', name='ticketsource'), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seva_id'], ['poojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seva_tickets_id'), 'seva_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_seva_tickets_mobile_number'), 'seva_tickets', ['mobile_number'], unique=False)
    op.create_index(op.f('ix_seva_tickets_qr_token'), 'seva_tickets', ['qr_token'], unique=True)
    op.create_index(op.f('ix_seva_tickets_seva_date'), 'seva_tickets', ['seva_date'], unique=False)
    op.create_index(op.f('ix_seva_tickets_source'), 'seva_tickets', ['source'], unique=False)
    op.create_index(op.f('ix_seva_tickets_status'), 'seva_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_seva_tickets_ticket_number'), 'seva_tickets', ['ticket_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seva_tickets_ticket_number'), table_name='seva_tickets')
    op.drop_index(op.f('ix_seva_tickets_status'), table_name='seva_tickets')
    op.drop_index(op.f('ix_seva_tickets_source'), table_name='seva_tickets')
    op.drop_index(op.f('ix_seva_tickets_seva_date'), table_name='seva_tickets')
    op.drop_index(op.f('ix_seva_tickets_qr_token'), table_name='seva_tickets')
    op.drop_index(op.f('ix_seva_tickets_mobile_number'), table_name='seva_tickets')
    op.drop_index(op.f('ix_seva_tickets_id'), table_name='seva_tickets')
    op.drop_table('seva_tickets')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_income_transactions_source_type'), table_name='income_transactions')
    op.drop_index(op.f('ix_income_transactions_payment_mode'), table_name='income_transactions')
    op.drop_table('income_transactions')
    op.drop_index(op.f('ix_gallery_id'), table_name='gallery')
    op.drop_table('gallery')
    op.drop_index(op.f('ix_expense_transactions_payment_mode'), table_name='expense_transactions')
    op.drop_index(op.f('ix_expense_transactions_category'), table_name='expense_transactions')
    op.drop_table('expense_transactions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_temples_id'), table_name='temples')
    op.drop_table('temples')
    op.drop_index(op.f('ix_poojas_id'), table_name='poojas')
    op.drop_table('poojas')
    op.drop_index(op.f('ix_festivals_id'), table_name='festivals')
    op.drop_table('festivals')
    op.drop_index(op.f('ix_donors_id'), table_name='donors')
    op.drop_table('donors')
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
