"""add_visitor_logs_v3

Revision ID: b385f6d4d9e5
Revises: 70f03626929a
Create Date: 2026-01-01 01:22:17.405904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b385f6d4d9e5'
down_revision: Union[str, None] = '70f03626929a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_hash', sa.String(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_logs_id'), 'visitor_logs', ['id'], unique=False)
    op.create_index(op.f('ix_visitor_logs_ip_hash'), 'visitor_logs', ['ip_hash'], unique=False)
    op.create_index(op.f('ix_visitor_logs_visit_date'), 'visitor_logs', ['visit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_logs_visit_date'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_ip_hash'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_id'), table_name='visitor_logs')
    op.drop_table('visitor_logs')
    # ### end Alembic commands ###
